BEGIN {
    print "\"use strict\"";
    print "// NOTE: This file is automatically generated by running generate-dispids-js.cmd from a razzle window.";
    print "Loader.OnLoad(function() {";
}

/^\"/ {
    print "    MSHTML.RegisterDispId(" $0 ");";
}

END {
    print "});"
}